version: '3'

services:
  machine-learning-client:
    build: ./machine-learning-client
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  web-app:
    build: ./web-app
    ports:
     - "3001:3001"
    depends_on:
      - "machine-learning-client"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
